name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ] # main 브랜치에 푸시될 때 작동

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew clean build -x test

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/fin-be:latest

    # [새로 추가된 단계] 깃허브의 설정 파일들을 GCP 서버로 복사
    - name: Copy Config Files to GCP
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.GCP_HOST }}
        username: ${{ secrets.GCP_USERNAME }}
        key: ${{ secrets.GCP_SSH_KEY }}
        source: "nginx/nginx.conf, docker-compose.yml" # 이 두 파일을 복사해서
        target: "~/fin-be" # 서버의 이 폴더에 넣습니다.

    - name: Deploy to GCP
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.GCP_HOST }}
        username: ${{ secrets.GCP_USERNAME }}
        key: ${{ secrets.GCP_SSH_KEY }}
        script: |
          # 서버의 프로젝트 폴더로 이동
          cd ~/fin-be
          
          # 최신 백엔드 이미지 다운로드
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/fin-be:latest
          
          # 컨테이너 재시작
          docker compose up -d
          
          # 안 쓰는 예전 이미지 찌꺼기 삭제 (용량 확보)
          docker image prune -f